version: "2"
services:
  mongo:
    image: mongo:3.6.3
    volumes:
      - ../data:/data/db
    ports:
      - "27017:27017"
  node_server:
    build: ./nodeServer
    volumes:
      - ./nodeServer:/src
    ports:
      - "8082:3000"
      - "9229:9229"
  ml_server:
    build: ./mlServer
    volumes:
      - ./mlServer:/app
    ports:
      - "8083:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=/app/app.py
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    

