version: "2"
services:
  mongo:
    image: mongo:3.6.3
    volumes:
      - ../data:/data/db
    ports:
      - "27017:27017"
  node_server:
    build: ./nodeServer
    volumes:
      - ./nodeServer:/src
    ports:
      - "8082:3000"
      - "9229:9229"

